### ISSUE TITLE
Is it possible to use DataFrameSuiteBase with FunSpec(scalatest)?

### ISSUE THREAD

**Issue by zekefast** [holdenk/spark-testing-base#108]
# Actual Results
I have a follow error in tests:

```
AdServerSpec.scala:28: class AdServerSpec inherits conflicting members:
[error]   method info in trait FunSpecLike of type => org.scalatest.Informer  and
[error]   method info in trait FunSuiteLike of type => org.scalatest.Informer
[error] (Note: this can be resolved by declaring an override in class AdServerSpec.);
[error]  other members with override errors are: note, alert, markup, registerTest, registerIgnoredTest, ignore, styleName
[error] class AdServerSpec extends FunSpec 
[error]       ^
[error] one error found
[error] (root/test:compileIncremental) Compilation failed
[error] Total time: 3 s, completed 09.05.2016 18:25:21
```

# Environment
* `spark-testing-base`: `0.3.2`
* `scala`: `2.11.7`
* `spark`: `1.6.1`
* `sbt`: `0.13.11` (not sure if relevant to the problem)

# Code

```scala
// AdServerSpec.scala
class AdServerSpec extends FunSpec 
  with DataFrameSuiteBase
  with MockFactory
  with Matchers
  with BeforeAndAfter
{
  // ...
}
```

# Question

Is it possible to use `DataFrameSuiteBase` along with `FunSpec` avoiding tedious overriding of all suggested methods? Shouldn't be class fixed to the way which make it possible to use with any base class for tests from scalatest?

**Comment by zekefast** [comment]
And when I tried to override conflicting methods in my test class I went into a bunch of nasty problems with signature conflicts and the biggest is overriding conflicted `val` as it does not allows to refer to [any parent implementation](https://issues.scala-lang.org/browse/SI-1938). 

```scala
  override def info                = super[FunSpec].info
  override def note                = super[FunSpec].note
  override def alert               = super[FunSpec].alert
  override def markup              = super[FunSpec].markup
  override def registerTest = super[FunSpec].registerTest _
  override def registerIgnoredTest = super[FunSpec].registerIgnoredTest _
  override def ignore              = super[FunSpec].ignore _
  override val styleName           = parentStyleName

  def parentStyleName: String = this.asInstanceOf[FunSpec].styleName
```

So, way to workaround or fix it would be greatly appreciated!

**Comment by mahmoudhanafy** [comment]
I will try to remove using `FunSuite` and make it more generic. That will be like what have been done here #102 .

**Comment by zekefast** [comment]
@mahmoudhanafy Thank you a lot! I can give a chance to `DataFrameSuiteBase` a second time now!

**Comment by ekrich** [comment]
I tried this using 1.6.0_0.4.1-preview but it is much slower than just using the following with `SharedSparkContext`.
```
val sqlContext = SQLContext.getOrCreate(sc)
import sqlContext.implicits._
```
I get the following output when using `DataFrameSuiteBase`. Notice it takes 34 seconds to run vs 8 seconds with the above. It would also be nice to get rid of the 2 lines of boiler plate as well but we are using an `val implicit sqlContext` so we don't have to explicitly pass the context around.
```
Run starting. Expected test count is: 1
DataFrameSpec:
16/07/21 14:19:48 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
16/07/21 14:19:58 WARN ObjectStore: Version information not found in metastore. hive.metastore.schema.verification is not enabled so recording the schema version 1.2.0
16/07/21 14:19:58 WARN ObjectStore: Failed to get database default, returning NoSuchObjectException
16/07/21 14:20:07 WARN DomainSocketFactory: The short-circuit local reads feature cannot be used because UNIX Domain sockets are not available on Windows.
16/07/21 14:20:16 WARN ObjectStore: Version information not found in metastore. hive.metastore.schema.verification is not enabled so recording the schema version 1.2.0
16/07/21 14:20:16 WARN ObjectStore: Failed to get database default, returning NoSuchObjectException
A DataFrame test
+---+---+
|  x|  y|
+---+---+
|  1|  4|
|  2|  3|
|  3|  2|
|  4|  1|
+---+---+

- should be able to initialize a spark context and sqlContext.
Run completed in 34 seconds, 570 milliseconds.
Total number of tests run: 1
Suites: completed 1, aborted 0
Tests: succeeded 1, failed 0, canceled 0, ignored 0, pending 0
All tests passed.
16/07/21 14:20:21 ERROR ShutdownHookManager: Exception while deleting Spark temp dir: C:\Users\erichardson\AppData\Local\Temp\spark-4a6aa854-145a-4f0d-ae22-d461a53bcfd9
java.io.IOException: Failed to delete: C:\Users\erichardson\AppData\Local\Temp\spark-4a6aa854-145a-4f0d-ae22-d461a53bcfd9
	at org.apache.spark.util.Utils$.deleteRecursively(Utils.scala:928)
	at org.apache.spark.util.ShutdownHookManager$$anonfun$1$$anonfun$apply$mcV$sp$3.apply(ShutdownHookManager.scala:65)
	at org.apache.spark.util.ShutdownHookManager$$anonfun$1$$anonfun$apply$mcV$sp$3.apply(ShutdownHookManager.scala:62)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at org.apache.spark.util.ShutdownHookManager$$anonfun$1.apply$mcV$sp(ShutdownHookManager.scala:62)
	at org.apache.spark.util.SparkShutdownHook.run(ShutdownHookManager.scala:267)
	at org.apache.spark.util.SparkShutdownHookManager$$anonfun$runAll$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(ShutdownHookManager.scala:239)
	at org.apache.spark.util.SparkShutdownHookManager$$anonfun$runAll$1$$anonfun$apply$mcV$sp$1.apply(ShutdownHookManager.scala:239)
	at org.apache.spark.util.SparkShutdownHookManager$$anonfun$runAll$1$$anonfun$apply$mcV$sp$1.apply(ShutdownHookManager.scala:239)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1765)
	at org.apache.spark.util.SparkShutdownHookManager$$anonfun$runAll$1.apply$mcV$sp(ShutdownHookManager.scala:239)
	at org.apache.spark.util.SparkShutdownHookManager$$anonfun$runAll$1.apply(ShutdownHookManager.scala:239)
	at org.apache.spark.util.SparkShutdownHookManager$$anonfun$runAll$1.apply(ShutdownHookManager.scala:239)
	at scala.util.Try$.apply(Try.scala:161)
	at org.apache.spark.util.SparkShutdownHookManager.runAll(ShutdownHookManager.scala:239)
	at org.apache.spark.util.SparkShutdownHookManager$$anon$2.run(ShutdownHookManager.scala:218)
	at org.apache.hadoop.util.ShutdownHookManager$1.run(ShutdownHookManager.java:54)
Exception during cleanup
```

**Comment by holdenk** [comment]
Thats a good point, I'll make a simplified version for shared usage - the current functionality keeps settings from bleeding over between tests - but for most people this likely isn't a big issue or they can do their own setup code. I'll create another issue for this.

**Comment by ekrich** [comment]
The newest preview works with Spec tests as the issue was merged. The speed issue has to do with the Hive stuff as shown in the warnings but to use the DataFrame compare feature I just use the current release as a basic `test("dataframe test") { ... }` type test and bare with the slowness. ScalaTest recommends the `test` approach as a starting point for people coming from JUnit. Honestly, I looked at ScalaTest source a bit, and integrating properly does take quite a bit of knowledge of how the system works. It is pretty complex.
