### ISSUE TITLE
Potential problem with transitive dependencies: org.eclipse.jetty

### ISSUE THREAD

**Issue by samouille666** [holdenk/spark-testing-base#116]
Hello,

I am experimenting a problem running test with spark-testing-base. Being from an expert in sbt I hope I do not err by addressing the problem here.
This is the stack I see:

```Java
2016-06-23 14:42:46 ERROR SparkContext:96 - Error initializing SparkContext.
java.lang.SecurityException: class "javax.servlet.FilterRegistration"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:898)
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:668)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:761)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.spark-project.jetty.servlet.ServletContextHandler.<init>(ServletContextHandler.java:136)
	at org.spark-project.jetty.servlet.ServletContextHandler.<init>(ServletContextHandler.java:129)
	at org.spark-project.jetty.servlet.ServletContextHandler.<init>(ServletContextHandler.java:98)
	at org.apache.spark.ui.JettyUtils$.createServletHandler(JettyUtils.scala:110)
	at org.apache.spark.ui.JettyUtils$.createServletHandler(JettyUtils.scala:101)
	at org.apache.spark.metrics.sink.MetricsServlet.getHandlers(MetricsServlet.scala:54)
	at org.apache.spark.metrics.MetricsSystem$$anonfun$getServletHandlers$2.apply(MetricsSystem.scala:91)
	at org.apache.spark.metrics.MetricsSystem$$anonfun$getServletHandlers$2.apply(MetricsSystem.scala:91)
	at scala.Option.map(Option.scala:145)
	at org.apache.spark.metrics.MetricsSystem.getServletHandlers(MetricsSystem.scala:91)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:534)
	at com.holdenkarau.spark.testing.SharedSparkContext$class.beforeAll(SharedSparkContext.scala:43)
	at TestMongoToHDFS.beforeAll(TestMongoToHDFS.scala:11)
	at org.scalatest.BeforeAndAfterAll$class.beforeAll(BeforeAndAfterAll.scala:187)
	at TestMongoToHDFS.beforeAll(TestMongoToHDFS.scala:11)
	at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:253)
	at TestMongoToHDFS.run(TestMongoToHDFS.scala:11)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:55)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2563)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2557)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2557)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1044)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1043)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2722)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1043)
	at org.scalatest.tools.Runner$.run(Runner.scala:883)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:138)javax.servlet by org.eclipse.jetty.orbit	3.0.0.v201112011016	
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

I have identified that the class belongs to: javax.servlet by org.eclipse.jetty.orbit	3.0.0.v201112011016	
from spark core. But as the problem occurs just in the test I thought that somebody could have and idea here.
I have checked but there seems to be just one version on this class and of the associated jar.

Does somebody has an idea ?

**Comment by samouille666** [comment]
A finally solved the problem. To those who are interested:

Conflict between two library that support a common, namespace (javax.servlet) and subset of object:

    org.eclipse.jetty.orbit (pulled by spark-test-base)
    servlet-api (pulled by any spark related jar: spark-core, spark-mlib, spark-hive, spark-sql)

we can solve the problem by excluding the namespace  "javax.servlet"  from the compile/runtime phase in the build.sbt
build.sbt
libraryDependencies += "org.apache.spark" %% "spark-mllib" % "1.5.2" excludeAll (ExclusionRule(organization = "javax.servlet"))
libraryDependencies += "org.apache.spark" %% "spark-core" % "1.5.2" excludeAll (ExclusionRule(organization = "javax.servlet"))
