### ISSUE TITLE
new build for spark 1.2.0

### ISSUE THREAD

**Issue by dicastro** [holdenk/spark-testing-base#121]
I would like a build of a recent version of spark-testing-base for spark 1.2.0.

I've tried with version 1.3.0_0.3.3 but I have an error in `JavaRDDComparisons.assertRDDEquals` that I think is because of incompatibility of versions 1.20 vs 1.3.0.

```
java.lang.NoClassDefFoundError: org/apache/spark/rdd/RDD$
    at com.holdenkarau.spark.testing.RDDComparisons$.compare(RDDComparisons.scala:108)
    at com.holdenkarau.spark.testing.JavaRDDComparisons$.compare(JavaRDDComparisons.scala:42)
    at com.holdenkarau.spark.testing.JavaRDDComparisons$.assertRDDEquals(JavaRDDComparisons.scala:29)
    at com.holdenkarau.spark.testing.JavaRDDComparisons.assertRDDEquals(JavaRDDComparisons.scala)
    at com.edelia.bc.elec.sensor.index.correction.service.SparkElecSensorIndexCorrectionServiceTest.test1(SparkElecSensorIndexCorrectionServiceTest.java:65)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.rdd.RDD$
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 30 more
```

**Comment by holdenk** [comment]
I don't think backporting to 1.2.0 is in the cards - Learning Spark is 1.3+ and 2.0 is coming out soon. Is there a reason you are using 1.2.0 or could upgrade?

**Comment by dicastro** [comment]
It is an existing project which has that version. It is not me who decide
to upgrade spark version.

Thank you, I will look for an alternative.

**Comment by holdenk** [comment]
I understand the frustration of wanting to use this with an older project, however as an open source maintainer there isn't a lot of fun in supporting really old versions. Now that the 2.1 has shipped I think its safe to say I'm never going to get around to shipping this for older 1.X versions, of course if someone wants to put in the effort to backport stuff I'll help with the code review but efforts would probably be better spent convincing people to upgrade (1.2.X has a lot of known issues).
