### ISSUE TITLE
DataFrameSuiteBase: assertDataFrameEquals throws a scalactic NoSuchMethodError

### ISSUE THREAD

**Issue by marminthibaut** [holdenk/spark-testing-base#132]
Hi,

I am working on a spark project written in scala / maven. I use spark-testing-base framework to execute my tests but when I do an `assertDataFrameEquals`, I got the following error:

```
An exception or error caused a run to abort: org.scalactic.Bool$.binaryMacroBool(Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;Z)Lorg/scalactic/Bool; 
java.lang.NoSuchMethodError: org.scalactic.Bool$.binaryMacroBool(Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;Z)Lorg/scalactic/Bool;
    at com.holdenkarau.spark.testing.TestSuite$class.assert(TestSuite.scala:13)
    at fr.***.***.***.FooSpec.assert(FooSpec.scala:8)
    at com.holdenkarau.spark.testing.DataFrameSuiteBaseLike$class.assertDataFrameEquals(DataFrameSuiteBase.scala:83)
    at fr.***.***.***.FooSpec.assertDataFrameEquals(FooSpec.scala:8)
    at fr.***.***.***.FooSpec$$anonfun$1.apply(FooSpec.scala:14)
    at fr.***.***.***.FooSpec$$anonfun$1.apply(FooSpec.scala:9)
    at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
...
```

Here are my pom dependencies and the test itself:

pom.xml:

```
    <properties>
        <spark.version>1.6.1</spark.version>
        <scala.version>2.10.6</scala.version>
        <scala.version.binary>2.10</scala.version.binary>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.scala-lang</groupId>
            <artifactId>scala-library</artifactId>
            <version>${scala.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-core_${scala.version.binary}</artifactId>
            <version>${spark.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-log4j12</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-sql_${scala.version.binary}</artifactId>
            <version>${spark.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-hive_${scala.version.binary}</artifactId>
            <version>${spark.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-streaming_${scala.version.binary}</artifactId>
            <version>${spark.version}</version>
        </dependency>
        <dependency>
            <groupId>com.oracle.drivers</groupId>
            <artifactId>ojdbc6</artifactId>
            <version>11.2.0.2.0</version>
        </dependency>
        <dependency>
            <groupId>com.databricks</groupId>
            <artifactId>spark-csv_${scala.version.binary}</artifactId>
            <version>1.4.0</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.1.7</version>
        </dependency>

        <!-- Test -->
        <!--<dependency>-->
            <!--<groupId>junit</groupId>-->
            <!--<artifactId>junit</artifactId>-->
            <!--<version>4.12</version>-->
            <!--<scope>test</scope>-->
        <!--</dependency>-->
        <dependency>
            <groupId>org.scalactic</groupId>
            <artifactId>scalactic_${scala.version.binary}</artifactId>
            <version>3.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.scalatest</groupId>
            <artifactId>scalatest_${scala.version.binary}</artifactId>
            <version>3.0.0</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.scalactic</groupId>
                    <artifactId>scalactic_${scala.version.binary}</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-all</artifactId>
            <version>1.10.19</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.holdenkarau</groupId>
            <artifactId>spark-testing-base_${scala.version.binary}</artifactId>
            <version>1.6.1_0.3.3</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-log4j12</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>
```

The FooSpec (from your sample code):

```
package fr.sihm.bifrost.refpers

import com.holdenkarau.spark.testing.DataFrameSuiteBase

class FooSpec extends DataFrameSuiteBase {
  test("awesomeTest") {
    val sqlCtx = sqlContext
    import sqlCtx.implicits._

    val input1 = sc.parallelize(List(1, 2, 3)).toDF
    assertDataFrameEquals(input1, input1) // equal

    val input2 = sc.parallelize(List(4, 5, 6)).toDF
    intercept[org.scalatest.exceptions.TestFailedException] {
      assertDataFrameEquals(input1, input2) // not equal
    }
  }
}
```

Any idea?

Thanks

**Comment by bryanv** [comment]
This is probably because you are specifying Scalatest 3.0.0 but spark-testing-base is built with 2.2.1.

**Comment by marminthibaut** [comment]
Oh thank you, I'll test it tomorrow

**Comment by ChipChopChippy** [comment]
I get the same error - I can run the sample code in a standalone project with no issues. But when I try to use the framework within an existing project (using Scalatest 3.0.0) I get the same NoSuchMethodError - as it's an existing project already using 3.0.0 I'm entering jar hell when I try to use 2.2.1 :(
Can we get a version compiled against 3.0.0? I haven't tried yet (and it may or may not be doable without a lot of time and energy) but can I raise a PR for this?

**Comment by holdenk** [comment]
I'll look at updating this to scalatest 3.0.0 soon, but for now closing this as not an issue with spark-testing-base rather issue with missmatched scalatest versions.
