### ISSUE TITLE
error when load a example

### ISSUE THREAD

**Issue by tivepro** [holdenk/spark-testing-base#135]
when I tried to execute this >
```
test("assert dataframes generated correctly") {
    val schema = StructType(List(StructField("name", StringType), StructField("age", IntegerType)))
    val sqlContext = new SQLContext(sc)
    val dataframeGen = DataframeGenerator.arbitraryDataFrame(sqlContext, schema)

    val property =
      forAll(dataframeGen.arbitrary) {
        dataframe => dataframe.schema === schema && dataframe.count >= 0
      }

    check(property)
  }
```

An exception or error caused a run to abort: Found class org.scalacheck.Gen, but interface was expected 
java.lang.IncompatibleClassChangeError: Found class org.scalacheck.Gen, but interface was expected
	at com.holdenkarau.spark.testing.DataframeGenerator$$anonfun$arbitraryDataFrameWithCustomFields$1.apply(DataframeGenerator.scala:42)
	at com.holdenkarau.spark.testing.DataframeGenerator$$anonfun$arbitraryDataFrameWithCustomFields$1.apply(DataframeGenerator.scala:42)
	at org.scalacheck.ArbitraryLowPriority$$anon$1.arbitrary$lzycompute(Arbitrary.scala:69)
	at org.scalacheck.ArbitraryLowPriority$$anon$1.arbitrary(Arbitrary.scala:69)

**Comment by tivepro** [comment]
```
object GenPrecio extends Properties("Precio"){
  import Prop.forAll
val genPrecio: Gen[Precio]={
    for {
.....
}yield ( N fields)
```
you have to specify all column values, it can be `StringColumn<- Arbitrary.arbitrary[String] `
```

property("Chequeamos que el precio es creado") = forAll (genPrecio) {
    (p:Precio ) => p.id_oferta!= " "
  }

}
```
this is the correct way to send a Generator for check labels in scala check
