### ISSUE TITLE
Checkpoint directory has not been set in the SparkContext

### ISSUE THREAD

**Issue by delenius** [holdenk/spark-testing-base#136]
I get this exception when I use spark-testing-base

```
Checkpoint directory has not been set in the SparkContext
org.apache.spark.SparkException: Checkpoint directory has not been set in the SparkContext
	at org.apache.spark.rdd.RDD.checkpoint(RDD.scala:1495)
	at pl.appsilon.marek.sparkdatalog.eval.DatabaseRepr$$anonfun$checkpoint$1.apply(DatabaseRepr.scala:13)
	at pl.appsilon.marek.sparkdatalog.eval.DatabaseRepr$$anonfun$checkpoint$1.apply(DatabaseRepr.scala:13)
	at scala.collection.MapLike$FilteredKeys$$anonfun$foreach$1.apply(MapLike.scala:231)
	at scala.collection.MapLike$FilteredKeys$$anonfun$foreach$1.apply(MapLike.scala:231)
	at scala.collection.immutable.Map$Map2.foreach(Map.scala:137)
	at scala.collection.MapLike$FilteredKeys.foreach(MapLike.scala:231)
```

I am using this version

```
libraryDependencies += "com.holdenkarau" % "spark-testing-base_2.11" % "2.0.0_0.4.5"

```

**Comment by holdenk** [comment]
It sounds like you are calling checkpoint but haven't set the checkpoint directory. You can do this by overriding the beforeAll or before to set the checkoointdirectory, but we could also do this by default for 0.6 (the only question is if having a local checkpoint dir is the right thing to do but that seems reasonable for testing).
