### ISSUE TITLE
ScalaTest 3.0.0 Support

### ISSUE THREAD

**Issue by NoOrdInaryGuy** [holdenk/spark-testing-base#137]
I'm not sure how widely used ScalaTest 3.0.0 is yet, but I was tinkering and noticed that as `spark-testing-base` depends on ScalaTest 2.2.6, you get `AbstractMethodError`s when trying to use it with a project that pulls in ScalaTest 3 - at least when using `RDDComparisons`.

This occurs during the class initialiser of RDDComparisons, due a dependency on org.scalatest.Assertions.

```
[info] com.xxx.MySpec *** ABORTED ***
[info]   java.lang.AbstractMethodError:
[info]   at org.scalatest.Assertions$class.$init$(Assertions.scala:1342)
[info]   at com.holdenkarau.spark.testing.RDDComparisons$.<init>(RDDComparisons.scala:28)
[info]   at com.holdenkarau.spark.testing.RDDComparisons$.<clinit>(RDDComparisons.scala)
```

~~I did check whether merely rebuilding `spark-testing-base` with ScalaTest at `3.0.0` works - but it looks like there were breaking changes, as the tests fail:~~

```
[info] com.holdenkarau.spark.testing.SampleScalaCheckTest *** ABORTED ***
[info]   java.lang.IncompatibleClassChangeError: Found interface org.scalacheck.Test$Parameters, but class was expected
[info]   at org.scalatest.prop.Configuration$class.getParams(Configuration.scala:444)
[info]   at com.holdenkarau.spark.testing.SampleScalaCheckTest.getParams(SampleScalaCheckTest.scala:27)
[info]   at org.scalatest.prop.Checkers$class.check(Checkers.scala:373)
[info]   at com.holdenkarau.spark.testing.SampleScalaCheckTest.check(SampleScalaCheckTest.scala:27)
[info]   at com.holdenkarau.spark.testing.SampleScalaCheckTest$$anonfun$1.apply(SampleScalaCheckTest.scala:36)
[info]   at com.holdenkarau.spark.testing.SampleScalaCheckTest$$anonfun$1.apply(SampleScalaCheckTest.scala:30)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
```

Edit: Realised the above is actually probably due to an incompatability between ScalaTest 3.0.0 and the version of ScalaCheck that this repo uses. I'll try and find some time to investigate more.

**Comment by aminaaslam** [comment]
I am also getting this error despite the fact that i am using ScalaTest 2.2.6.Any guidance in this regard would be highly appreciative
java.lang.IncompatibleClassChangeError
	at org.apache.spark.internal.Logging$class.$init$(Logging.scala:35)
	at com.holdenkarau.spark.testing.Utils$.<init>(Utils.scala:33)
	at com.holdenkarau.spark.testing.Utils$.<clinit>(Utils.scala)
	at com.holdenkarau.spark.testing.JavaRDDComparisons$.compareRDD(JavaRDDComparisons.scala:41)
	at com.holdenkarau.spark.testing.JavaRDDComparisons$.assertRDDEquals(JavaRDDComparisons.scala:29)
	at com.holdenkarau.spark.testing.JavaRDDComparisons.assertRDDEquals(JavaRDDComparisons.scala)
	at com.baesystems.ai.analytics.util.RDDUtilTest.verifyHistogramTest(RDDUtilTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by holdenk** [comment]
So the latest release of spark-testing-base now uses 3.0.0. I'm going to close this but if anyone runs into IncompatableClassChangeError feel free to open a new issue.
