### ISSUE TITLE
illegal inheritance ERROR

### ISSUE THREAD

**Issue by honeyAndSw** [holdenk/spark-testing-base#142]
Hi all,

I'm trying to integrate spark-testing-base into my project, and have an issue.
In the following test, IDE says **"Cannot resolve symbol `test`"**.
```
class RealTimeStatsTest extends StreamingSuiteBase {

  type StringPair = (String, String)
  type IntegerPair = (Integer, Integer)

  test("Send string input") {
    val input = List()
    val output = List()

    testOperation[StringPair, IntegerPair](
      input, updateStateByKeyOperation _, output, ordered = false)
  }

  def updateStateByKeyOperation(stream: DStream[StringPair]): DStream[IntegerPair] = ??? 
```

Versions are:
* spark-testing-base_2.19:1.6.2_0.4.5
* scala 1.10.5
* Two scalatest are found in IntelliJ External Libraries: scalatest:0.9.1 and scalatest_2.19:2.2.6, I explicitly import none of them though. I just think this is where the error occurs.

**Comment by dkick** [comment]
For what it's worth, I'm finding the same thing with

`import com.holdenkarau.spark.testing.StreamingSuiteBase

class MyTest extends StreamingSuiteBase {
  test("MyTest") {
    val inputs = List()
    val expect = List()
    testOperation[JsonString, JsonString](
      inputs, Service.toReport _, expect, ordered=false)
  }
}
`

... using ...

`scalaVersion := "2.11.8"

lazy val sparkVersion = "2.0.1"
lazy val sparkTestVersion = sparkVersion + "_0.4.7"

libraryDependencies ++= Seq(
  "com.holdenkarau" %% "spark-testing-base" % sparkTestVersion % "test"
    withSources(),
  "io.argonaut" %% "argonaut" % "6.1",
  "org.apache.spark" %% "spark-core" % sparkVersion,
  "org.apache.spark" %% "spark-streaming" % sparkVersion,
  "org.scalatest" %% "scalatest" % "3.0.0" % "test" withSources(),
  "org.scalaz" %% "scalaz-core" % "7.1.1")
`

Giving

`[error]  self-type MyTest does not conform to com.holdenkarau.spark.testing.StreamingSuiteBase's selftype com.holdenkarau.spark.testing.StreamingSuiteBase with org.scalatest.Suite
[error] class MyTest extends StreamingSuiteBase {
[error]                             ^
[error] MyTest.scala:6: package test is not a value
[error]   test("MyTest") {
[error]   ^
[error] two errors found
[error] (test:compileIncremental) Compilation failed
[error] Total time: 1 s, completed Oct 13, 2016 3:25:01 PM
`

**Comment by dkick** [comment]
However, if I add ...

`  self: org.scalatest.Suite =>`

... then I only get ...

`[error] MyTest.scala:8: package test is not a value`
`[error]   test("MyTest") {`
`[error]   ^`
`[error] one error found`

**Comment by dkick** [comment]
Okay, one more revision: if I can the code to be as follows

```
class MyTest extends FlatSpec with StreamingSuiteBase {
  "MyTest" {
    val give = List(List(JsonString("")))
    val work = Service.callsToReport _
    val want = List()
    testOperation[JsonString, JsonString](give, work, want, ordered=false)
    1
  }
}
```

This compiles.  But then does not run.

```
> test
[info] Compiling 1 Scala source to .../target/scala-2.11/test-classes...
[info] MyTest:
[info] MyTest *** ABORTED ***
[info]   java.lang.IllegalArgumentException: requirement failed: Spark Streaming cannot be initialized with both SparkContext and checkpoint as null
[info]   at scala.Predef$.require(Predef.scala:224)
[info]   at org.apache.spark.streaming.StreamingContext.<init>(StreamingContext.scala:131)
[info]   at org.apache.spark.streaming.TestStreamingContext.<init>(TestStreamingContext.scala:28)
[info]   at org.apache.spark.streaming.TestStreamingContext.<init>(TestStreamingContext.scala:35)
[info]   at com.holdenkarau.spark.testing.StreamingSuiteCommon$class.setupStreams(StreamingSuiteCommon.scala:141)
[info]   at MyTest.setupStreams(MyTest.scala:6)
[info]   at com.holdenkarau.spark.testing.StreamingSuiteBase$class.testOperation(StreamingSuiteBase.scala:150)
[info]   at MyTest.testOperation(MyTest.scala:6)
[info]   at MyTest.<init>(MyTest.scala:11)
[info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[info]   ...
[info] ScalaCheck
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] ScalaTest
[info] Run completed in 198 milliseconds.
[info] Total number of tests run: 0
[info] Suites: completed 0, aborted 1
[info] Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
[info] *** 1 SUITE ABORTED ***
[error] Error: Total 1, Failed 0, Errors 1, Passed 0
[error] Error during tests:
[error] 	MyTest
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 2 s, completed Oct 13, 2016 4:52:31 PM
> 
```

So ... I can get code which does not seem to match the documentation to compile but then not run.  Have I wandered into a version which is not yet meant for prime time?

**Comment by hannahlaura44** [comment]
I'm using scala 2.11.8 and spark-testing-base 2.0.0_0.4.7 and having the same issues:

My code:

```
import com.holdenkarau.spark.testing.StreamingSuiteBase
import co.verdigris.swarm.BMSReadingsFixture._
import co.verdigris.swarm.BMSReadingsProcessor.{parseReading, parseStream}

class BMSReadingsProcessorStreamingTest extends StreamingSuiteBase {

  test("parse readings") {
    val input = List(List(readingStringFixture))
    testOperation(input, parseStream, List(List()))
  }
}
```
Compile Errors:
```
Error:(39, 49) illegal inheritance;
 self-type co.verdigris.swarm.BMSReadingsProcessorStreamingTest does not conform to com.holdenkarau.spark.testing.StreamingSuiteBase's selftype com.holdenkarau.spark.testing.StreamingSuiteBase with org.scalatest.Suite
class BMSReadingsProcessorStreamingTest extends StreamingSuiteBase {

Error:(41, 3) package test is not a value
  test("parse readings") {
```


I haven't been able to find much documentation or examples for the latest release (2.0.0_0.4.7)
@holdenk have you posted documentation for the new release?

@honeyAndSw @dkick were either of you able to find a solution to these issues?

**Comment by honeyAndSw** [comment]
@hannahlaura44 nope. 😞

**Comment by ponkin** [comment]
Same issue (

**Comment by dkick** [comment]
@hannahlaura44: I've moved onto other things, so I haven't been looking at this issue.

**Comment by holdenk** [comment]
So the best documentation for this is the sample test associated, (e.g. https://github.com/holdenk/spark-testing-base/blob/8ebcf8b27921f82bf3d305d4e98c4bbcc8c01f32/src/test/1.3/scala/com/holdenkarau/spark/testing/SampleStreamingTest.scala )

My guess is that you need to extend `FunSuite` as well
