### ISSUE TITLE
Exception encountered when attempting to run a suite - NoClassDefFoundError: org/apache/hadoop/hive/conf/HiveConf$ConfVars

### ISSUE THREAD

**Issue by jabenitez** [holdenk/spark-testing-base#143]
I followed the example for dataframe test:

```
case class TwoNumbers(x: Double, y: Double)

//class DataFrameUtilsTest extends DataFrameSuiteBase {
class DataFrameUtilsTest extends FunSuite with DataFrameSuiteBase {
  import spark.implicits._

    test("simple test") {
      val primitiveDS = Seq(1, 2, 3).toDS()
      val input1 = Seq(TwoNumbers(1, 1.1), TwoNumbers(2, 2.2), TwoNumbers(3, 3.3)).toDF()
      val input2 = Seq(TwoNumbers(1, 1.2), TwoNumbers(2, 2.3), TwoNumbers(3, 3.4)).toDF()
      assertDataFrameApproximateEquals(input1, input2, 0.11) // equal
  
      intercept[org.scalatest.exceptions.TestFailedException] {
        assertDataFrameApproximateEquals(input1, input2, 0.05) // not equal
      }
    }
}
```

I have spark 2.0.0 and scala 2.11.8

When I execute

`sbt test`, I get the following message:

```
[info] DataFrameUtilsTest:
[info] Exception encountered when attempting to run a suite with class name: com.testme.utils.DataFrameUtilsTest *** ABORTED *** (2 seconds, 749 milliseconds)
[info]   java.lang.NoClassDefFoundError: org/apache/hadoop/hive/conf/HiveConf$ConfVars
[info]   at com.holdenkarau.spark.testing.DataFrameSuiteBaseLike$class.newBuilder$1(DataFrameSuiteBase.scala:67)
[info]   at com.holdenkarau.spark.testing.DataFrameSuiteBaseLike$class.sqlBeforeAllTestCases(DataFrameSuiteBase.scala:81)
[info]   at com.testme.utils.DataFrameUtilsTest.com$holdenkarau$spark$testing$DataFrameSuiteBase$$super$sqlBeforeAllTestCases(DataFrameUtilsTest.scala:13)
[info]   at com.holdenkarau.spark.testing.DataFrameSuiteBase$class.beforeAll(DataFrameSuiteBase.scala:41)
[info]   at com.tesme.utils.DataFrameUtilsTest.beforeAll(DataFrameUtilsTest.scala:13)
[info]   at org.scalatest.BeforeAndAfterAll$class.beforeAll(BeforeAndAfterAll.scala:187)
[info]   at com.testme.utils.DataFrameUtilsTest.beforeAll(DataFrameUtilsTest.scala:13)
[info]   at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:253)
[info]   at com.testme.utils.DataFrameUtilsTest.run(DataFrameUtilsTest.scala:13)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:357)
[info]   ...
[info]   Cause: java.lang.ClassNotFoundException: org.apache.hadoop.hive.conf.HiveConf$ConfVars
[info]   at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[info]   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[info]   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[info]   at com.holdenkarau.spark.testing.DataFrameSuiteBaseLike$class.newBuilder$1(DataFrameSuiteBase.scala:67)
[info]   at com.holdenkarau.spark.testing.DataFrameSuiteBaseLike$class.sqlBeforeAllTestCases(DataFrameSuiteBase.scala:81)
[info]   at com.testme.utils.DataFrameUtilsTest.com$holdenkarau$spark$testing$DataFrameSuiteBase$$super$sqlBeforeAllTestCases(DataFrameUtilsTest.scala:13)
[info]   at com.holdenkarau.spark.testing.DataFrameSuiteBase$class.beforeAll(DataFrameSuiteBase.scala:41)
[info]   at com.testme.utils.DataFrameUtilsTest.beforeAll(DataFrameUtilsTest.scala:13)
[info]   at org.scalatest.BeforeAndAfterAll$class.beforeAll(BeforeAndAfterAll.scala:187)
[info]   at com.testme.utils.DataFrameUtilsTest.beforeAll(DataFrameUtilsTest.scala:13)
[info]   ...

```

**Comment by holdenk** [comment]
Ah it seems like you need the hive dependencies as well, at least as test dependencies (e.g. spark-hive)

**Comment by jabenitez** [comment]
Thank you @holdenk  in fact! Now it works after I added 

`  "org.apache.spark" %% "spark-hive" % "2.0.0"` to my build.sbt.

**Comment by holdenk** [comment]
Awesome :)

**Comment by leobenkel** [comment]
you can also do 
```  override protected implicit def enableHiveSupport: Boolean = false
``` ?
