### ISSUE TITLE
java.lang.IncompatibleClassChangeError

### ISSUE THREAD

**Issue by aminaaslam** [holdenk/spark-testing-base#163]
I am getting this error while running a very simple unit test case.
using these versions 
spark-testing-base_2.10.version "2.0.0_0.4.7"
<dependency org="com.holdenkarau" name="spark-testing-base_2.10" rev="&spark-testing-base_2.10.version;" conf="prod->default"/> 
<dependency org="org.hamcrest" name="hamcrest-core" rev="1.3"/>
<dependency org="org.scalatest" name="scalatest_2.11" rev="2.2.6"/> 

This problem occurs on this line 
// Run the assertions on the result and expected
	    JavaRDDComparisons.assertRDDEquals(
	        JavaRDD.fromRDD(JavaPairRDD.toRDD(result), tag),
	        JavaRDD.fromRDD(JavaPairRDD.toRDD(expectedRDD), tag));
I am aware of this issue ScalaTest 3.0.0 Support #137 but it am not using ScalaTest

java.lang.IncompatibleClassChangeError
	at org.apache.spark.internal.Logging$class.$init$(Logging.scala:35)
	at com.holdenkarau.spark.testing.Utils$.<init>(Utils.scala:33)
	at com.holdenkarau.spark.testing.Utils$.<clinit>(Utils.scala)
	at com.holdenkarau.spark.testing.JavaRDDComparisons$.compareRDD(JavaRDDComparisons.scala:41)
	at com.holdenkarau.spark.testing.JavaRDDComparisons$.assertRDDEquals(JavaRDDComparisons.scala:29)
	at com.holdenkarau.spark.testing.JavaRDDComparisons.assertRDDEquals(JavaRDDComparisons.scala)
	at com.baesystems.ai.analytics.util.RDDUtilTest.verifyHistogramTest(RDDUtilTest.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by holdenk** [comment]
Which version of Spark & Scala & Log4J are you using?

**Comment by aminaaslam** [comment]
I am using Spark 2.0.2, scala.version "2.11" and slf4j-log4j12-1.7.16

**Comment by aminaaslam** [comment]
Any help in this regard would be very helpful. Can someone guide me as to why i am getting this error.

**Comment by holdenk** [comment]
You have a mismatched version of Spark and Spark testing base, if the logging classes (or log4j versions) has changed at all between 2.0.0 and 2.0.2 that would explain the exception. Can you try this with a matching version?

**Comment by GouravGit** [comment]
I am getting a same kind of error but not able to figure out what the actual cause is. In my case the version is correct though (I think).

<maven.compiler.source>1.8</maven.compiler.source>
<maven.compiler.target>1.8</maven.compiler.target>
<encoding>UTF-8</encoding>
<scala.tools.version>2.11</scala.tools.version>
<scala.version>2.11.8</scala.version>
<spark.version>2.0.0</spark.version>
<databricks.csv.version>1.4.0</databricks.csv.version>
<databricks.xml.version>0.4.1</databricks.xml.version>

<dependency>
	<groupId>com.holdenkarau</groupId>
	<artifactId>spark-testing-base_2.11</artifactId>
	<version>2.0.0_0.7.1</version>
	<scope>test</scope>
</dependency>



SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/gdutta2/.m2/repository/org/slf4j/slf4j-log4j12/1.7.10/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/gdutta2/.m2/repository/org/slf4j/slf4j-log4j12/1.7.16/slf4j-log4j12-1.7.16.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
17/09/11 03:00:49 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
java.lang.IncompatibleClassChangeError: Class com.holdenkarau.spark.testing.Utils$ does not implement the requested interface org.apache.spark.internal.Logging
	at org.apache.spark.internal.Logging$class.$init$(Logging.scala:35)
	at com.holdenkarau.spark.testing.Utils$.<init>(Utils.scala:33)
	at com.holdenkarau.spark.testing.Utils$.<clinit>(Utils.scala)
	at com.holdenkarau.spark.testing.SparkContextProvider$class.setup(SparkContextProvider.scala:45)
	at com.metlife.adr.lrm.test.LrmTest.setup(LrmTest.scala:24)
	at com.holdenkarau.spark.testing.SharedSparkContext$class.beforeAll(SharedSparkContext.scala:38)
	at com.metlife.adr.lrm.test.LrmTest.com$holdenkarau$spark$testing$DataFrameSuiteBase$$super$beforeAll(LrmTest.scala:24)
	at com.holdenkarau.spark.testing.DataFrameSuiteBase$class.beforeAll(DataFrameSuiteBase.scala:41)
	at com.metlife.adr.lrm.test.LrmTest.beforeAll(LrmTest.scala:39)
	at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:212)
	at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
	at com.metlife.adr.lrm.test.LrmTest.run(LrmTest.scala:24)
	at org.scalatest.junit.JUnitRunner.run(JUnitRunner.scala:99)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by wuzhim** [comment]
I met the same problem. I put spark-testing-basing in the first of your dependencies. I do not know why this could solve this problem, but it worked for me. Hope that could help somebody.
