### ISSUE TITLE
intellij IDEA failing to execute tests properly

### ISSUE THREAD

**Issue by geoHeil** [holdenk/spark-testing-base#170]
When using a project setup like https://github.com/geoHeil/sparkTestScalaStrangeIDEAError with a test of https://github.com/geoHeil/sparkTestScalaStrangeIDEAError/blob/master/src/test/scala/Foo.scala#L4-L16 (from the spark-testing-base wiki it will compile and execute fine in sbt, but when using IntelliJ IDEA the UI will display an error about not having implemented a function from the superclass. When executing the test in the UI either I get a compile error up front, or the test will fail to execute successfully - even when sbt test is green.

**Comment by holdenk** [comment]
That's weird and seems like possibly an IntelliJ issue (maybe create a parallel issue with them?) I don't use IntelliJ - can you past the error(s) you get and I can take a look later this week to see if I can think of anything.

**Comment by geoHeil** [comment]
@holdenk  I did that already here https://youtrack.jetbrains.com/issue/IDEA-169871

The exact error in the syntax highlighting is

`class test must be declared abstract or implement abstract member 'withFixture'(test: Any): Outcome in scalaTestSuite Mixing
`
and the bug/errors wenn clicking the run / play symbol

```
Error:(13, 61) could not find implicit value for parameter pos: org.scalactic.source.Position
    intercept[org.scalatest.exceptions.TestFailedException] {
Error:(13, 61) not enough arguments for method intercept: (implicit classTag: scala.reflect.ClassTag[org.scalatest.exceptions.TestFailedException], implicit pos: org.scalactic.source.Position)org.scalatest.exceptions.TestFailedException.
Unspecified value parameter pos.
    intercept[org.scalatest.exceptions.TestFailedException] {
Error:(5, 23) could not find implicit value for parameter pos: org.scalactic.source.Position
  test("simple test") {
```
this is for right click test.
Strangely after the first run configuration has been setup clicking onto the play symbol on the far top right-hand corner (when this config is selected) no compile errors will happen. Rather the test will fail during runtime:

```
Testing started at 21:12 ...
17/03/19 21:12:08 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
17/03/19 21:12:14 WARN SparkContext: Using an existing SparkContext; some configuration may not take effect.
17/03/19 21:12:22 WARN ObjectStore: Version information not found in metastore. hive.metastore.schema.verification is not enabled so recording the schema version 1.2.0
17/03/19 21:12:23 WARN ObjectStore: Failed to get database default, returning NoSuchObjectException
17/03/19 21:12:23 WARN ObjectStore: Failed to get database global_temp, returning NoSuchObjectException

An exception or error caused a run to abort: org.scalatest.Assertions$AssertionsHelper.macroAssert(Lorg/scalactic/Bool;Ljava/lang/Object;Lorg/scalactic/Prettifier;Lorg/scalactic/source/Position;)Lorg/scalatest/compatible/Assertion; 
java.lang.NoSuchMethodError: org.scalatest.Assertions$AssertionsHelper.macroAssert(Lorg/scalactic/Bool;Ljava/lang/Object;Lorg/scalactic/Prettifier;Lorg/scalactic/source/Position;)Lorg/scalatest/compatible/Assertion;
	at com.holdenkarau.spark.testing.TestSuite$class.assert(TestSuite.scala:19)
	at test.assert(Foo.scala:4)
	at com.holdenkarau.spark.testing.DatasetSuiteBaseLike$class.assertDatasetEquals(DatasetSuiteBase.scala:46)
	at test.assertDatasetEquals(Foo.scala:4)
	at test$$anonfun$1.apply$mcV$sp(Foo.scala:10)
	at test$$anonfun$1.apply(Foo.scala:5)
	at test$$anonfun$1.apply(Foo.scala:5)
	at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:166)
	at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
	at org.scalatest.FunSuite.withFixture(FunSuite.scala:1555)
	at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:163)
	at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175)
	at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
	at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:175)
	at org.scalatest.FunSuite.runTest(FunSuite.scala:1555)
	at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:208)
	at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:208)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
	at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:208)
	at org.scalatest.FunSuite.runTests(FunSuite.scala:1555)
	at org.scalatest.Suite$class.run(Suite.scala:1424)
	at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1555)
	at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:212)
	at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:212)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
	at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:212)
	at test.org$scalatest$BeforeAndAfterAll$$super$run(Foo.scala:4)
	at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:257)
	at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:256)
	at test.run(Foo.scala:4)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:55)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2563)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2557)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2557)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1044)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1043)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2722)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1043)
	at org.scalatest.tools.Runner$.run(Runner.scala:883)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:138)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)


Process finished with exit code 0

```

**Comment by ecurtin** [comment]
@geoHeil I'm not 100% positive on this, but you might be experiencing the same scalatest version conflict that I was. 

Importing the spark-testing-base like this seems to have fixed my issue: 
```
"com.holdenkarau" %% "spark-testing-base" % "YOUR SPARK VERSION_0.6.0" % "test" excludeAll(
  ExclusionRule(organization = "org.scalacheck"),
  ExclusionRule(organization = "org.scalactic"),
  ExclusionRule(organization = "org.scalatest")
)
```

**Comment by geoHeil** [comment]
@ecurtin I tried it. Indeed this is the solution. So you suggest it is a mixup between spark-testing-base sparks dependency? 

Below works fine for me. But to use the **current** version of scale test how should the statement be formulated? I would not want to add the `ExcluseionRule` for each spark dependency.
```

libraryDependencies ++= Seq(
  "org.apache.spark" %% "spark-core" % spark % "provided",
  "org.apache.spark" %% "spark-sql" % spark % "provided",
  "org.apache.spark" %% "spark-hive" % spark % "provided",
  "com.holdenkarau" % "spark-testing-base_2.11" % s"${spark}_0.6.0" % "test" excludeAll(
  ExclusionRule(organization = "org.scalacheck"),
  ExclusionRule(organization = "org.scalactic"),
  ExclusionRule(organization = "org.scalatest")
)
)
```

**Comment by geoHeil** [comment]
I will use
```
libraryDependencies ++= Seq(
  "org.apache.spark" %% "spark-core" % spark % "provided",
  "org.apache.spark" %% "spark-sql" % spark % "provided",
  "org.apache.spark" %% "spark-hive" % spark % "provided")
  .map(_.excludeAll(
    ExclusionRule(organization = "org.scalacheck"),
    ExclusionRule(organization = "org.scalactic"),
    ExclusionRule(organization = "org.scalatest")
  ))

libraryDependencies ++= Seq(
  "com.holdenkarau" % "spark-testing-base_2.11" % s"${spark}_0.6.0" % "test"
)
```

**Comment by ecurtin** [comment]
Glad it worked! I think your solution of excluding from Spark instead of spark-testing-base is perfectly valid.

**Comment by ravikirancap** [comment]
@geoHeil @holdenk : i am facing the same issue when using the version 0.7.2 of spark-testing-base. However, it seems to work fine with 0.6.0 upon using the above solution
