### ISSUE TITLE
NPE when using SparkSession from DataFrameSuiteBase

### ISSUE THREAD

**Issue by bbarker** [holdenk/spark-testing-base#180]
Simple test case ([complete MWE project](https://github.com/bbarker/ProjectGists/tree/master/Scala/SparkSessionTester) with `build.sbt`):

```scala
import com.holdenkarau.spark.testing.DataFrameSuiteBase
import org.junit.Test
import org.scalatest.FunSuite

import org.apache.spark.sql.SparkSession


class SessionTest extends FunSuite with DataFrameSuiteBase {

  implicit val sparkImpl: SparkSession = spark

  @Test
  def simpleLookupTest {

    val homeDir = System.getProperty("user.home")
    val training = spark.read.format("libsvm")
      .load(s"$homeDir\\Documents\\GitHub\\sample_linear_regression_data.txt")
    println("completed simple lookup test")
  }

}
```

The result of running this with JUnit is an NPE at the  load line:

```

java.lang.NullPointerException
	at SessionTest.simpleLookupTest(SessionTest.scala:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

Note it shouldn't matter that the file being loaded exists or not; in a properly configured SparkSession, a more sensible error will be thrown.

**Comment by ecurtin** [comment]
Try mixing in `with BeforeAndAfterAll`. I was getting an NPE with my spark value and it turns out that it needs to be initialized in a beforeAll call.

**Comment by bbarker** [comment]
@ecurtin Thanks! FYI, I seem to have generated some interest in the more general context of the question at http://stackoverflow.com/questions/43729262/how-to-write-unit-tests-in-spark-2-0 but it sounds like you may have a specific answer ... hope to get back to this very soon.

**Comment by nburbank** [comment]
hey @ecurtin can you share exactly how you fixed this? i'm not managing to get it to work by initializing spark in `BeforeAndAfterAll` - thanks!

**Comment by ecurtin** [comment]
@nburbank Howdy, in this particular test I had to use beforeAll and afterAll to do some data setup, and I kept getting an NPE for `spark` or `sc` when I tried to switch to SharedSparkContext. But when I added the call to super.beforeAll(), it initialized `spark` (or `sc`, depending). So:
```
import com.holdenkarau.spark.testing.DataFrameSuiteBase
import org.scalatest.{BeforeAndAfterAll, FlatSpec, Matchers}

class ConfigFileTest extends FlatSpec with Matchers with BeforeAndAfterAll with DataFrameSuiteBase {

  override def beforeAll(): Unit = {
    super.beforeAll()
    // and then setup my data and stuff
  }
  override def afterAll(): Unit = {
    // teardown my own stuff
    super.afterAll()
  }

  "And now, because I made the call to the super funcs, my SparkSession" should "not be null" in {
    spark shouldNot be null
  }
```

**Comment by Chandrakanth66326632** [comment]
Hi All,
Even I am facing similar issue my code is throwing a NPE when sparksession is being loaded. 
Unfortunately, the Spark session code is in the other class, i am invoking the method using the classname reference.
I am already having a SparkContext running.
Can i have two spark contexts during run time?
How do I overcome the problem, any suggestions.

**Comment by VladimirApolaiko** [comment]
I you want to know the reason of this issue, read the following:
spark val is stored in here:
@transient lazy val spark: SparkSession = SparkSessionProvider._sparkSession

This constant is lazy and initialized with SparkSessionProvider._sparkSession, by default its value is null
@transient var _sparkSession: SparkSession = _

_sparkSession is initialized in method sqlBeforeAllTestCases:
override def beforeAll() {
    super.beforeAll()
    super.sqlBeforeAllTestCases()
  }

but method beforeAll is called after
implicit val sparkImpl: SparkSession = spark

Therefore this code get the value of lazy constant, which get the value of SparkSessionProvider._sparkSession, which is null in the moment this code executing

**Comment by minnieshi** [comment]
I found I had to set up some DF in fixture instead of the beforeAll section. 
Not sure better way can be done.
