### ISSUE TITLE
Guava Stopwatch bug

### ISSUE THREAD

**Issue by denisgarci** [holdenk/spark-testing-base#191]
Hi,

I'm using spark-testing-base to test a Spark 1.6 and Elasticsearch app. The following bug is happening:
https://issues.apache.org/jira/browse/HADOOP-11032

Overriding the Hadoop dependencies to 2.7.3 of spark-testing-base fixes the bug. Any plans to upgrade Hadoop in a future release?

**Comment by holdenk** [comment]
That's a good point. If you want to make a PR to update us to 2.7.3 I think that could be a reasonable version to depend on going forward (probably just a matter of updating build.sbt and making sure everything still builds and passes ok).

**Comment by denisgarci** [comment]
@holdenk thanks for the prompt answer! I have a branch [here](https://github.com/denisgarci/spark-testing-base/tree/update-hadoop) but two suites are failing. `YARNClusterTest` with the following error
```
[info] com.holdenkarau.spark.testing.YARNClusterTest *** ABORTED ***
[info]   org.apache.spark.SparkException: Yarn application has already ended! It might have been killed or unable to launch application master.
[info]   at org.apache.spark.scheduler.cluster.YarnClientSchedulerBackend.waitForApplication(YarnClientSchedulerBackend.scala:85)
[info]   at org.apache.spark.scheduler.cluster.YarnClientSchedulerBackend.start(YarnClientSchedulerBackend.scala:62)
[info]   at org.apache.spark.scheduler.TaskSchedulerImpl.start(TaskSchedulerImpl.scala:156)
[info]   at org.apache.spark.SparkContext.<init>(SparkContext.scala:509)
[info]   at com.holdenkarau.spark.testing.YARNClusterTest.beforeAll(YARNClusterTest.scala:17)
[info]   at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:212)
[info]   at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
[info]   at com.holdenkarau.spark.testing.YARNClusterTest.run(YARNClusterTest.scala:7)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
```
and `SampleMiniClusterTest` with the following error
```
17/06/09 10:01:48 ERROR SparkContext: Error initializing SparkContext.
org.apache.spark.SparkException: Yarn application has already ended! It might have been killed or unable to launch application master.
	at org.apache.spark.scheduler.cluster.YarnClientSchedulerBackend.waitForApplication(YarnClientSchedulerBackend.scala:85)
	at org.apache.spark.scheduler.cluster.YarnClientSchedulerBackend.start(YarnClientSchedulerBackend.scala:62)
	at org.apache.spark.scheduler.TaskSchedulerImpl.start(TaskSchedulerImpl.scala:156)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:509)
	at com.holdenkarau.spark.testing.SharedMiniCluster$class.beforeAll(SharedMiniCluster.scala:49)
	at com.holdenkarau.spark.testing.SampleMiniClusterTest.beforeAll(SampleMiniClusterTest.scala:23)
	at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:212)
	at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
	at com.holdenkarau.spark.testing.SampleMiniClusterTest.run(SampleMiniClusterTest.scala:23)
	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
	at sbt.ForkMain$Run$2.call(ForkMain.java:296)
	at sbt.ForkMain$Run$2.call(ForkMain.java:286)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Any idea how to fix these errors?

**Comment by holdenk** [comment]
Thanks for working on that! So my guess is that parts of the YarnCluster test need to be updated, its based on YarnClusterSuite.scala from the Spark project, so I'd take a quick look through their as a starting point.
