### ISSUE TITLE
Incompability with hbase-testing-util

### ISSUE THREAD

**Issue by epahomov** [holdenk/spark-testing-base#205]
I have dep in my tests on 

testCompile group: 'org.apache.hbase', name: 'hbase-testing-util', version: "1.2.0-cdh5.11.0", 

when I add 

testCompile group: 'com.holdenkarau', name: "spark-testing-base_${scalaVersion}", version: "${sparkVersion}_0.7.2"

I get exception running my Java tests, which work with hbase and do not work with spark 

`java.lang.NoSuchFieldError: IS_SECURITY_ENABLED
	at org.apache.jasper.compiler.JspRuntimeContext.<init>(JspRuntimeContext.java:197)
	at org.apache.jasper.servlet.JspServlet.init(JspServlet.java:150)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.servlet.ServletHandler.initialize(ServletHandler.java:736)
	at org.mortbay.jetty.servlet.Context.startContext(Context.java:140)
	at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1282)
	at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:518)
	at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:499)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.handler.HandlerCollection.doStart(HandlerCollection.java:152)
	at org.mortbay.jetty.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:156)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
	at org.mortbay.jetty.Server.doStart(Server.java:224)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.apache.hadoop.hbase.http.HttpServer.start(HttpServer.java:954)
	at org.apache.hadoop.hbase.http.InfoServer.start(InfoServer.java:91)`

Seems like dep issue.

**Comment by holdenk** [comment]
hmmm, what happens if you exclude the hive dep?
