### ISSUE TITLE
 java.io.IOException: failure to login: No LoginModules configured for hadoop_simple

### ISSUE THREAD

**Issue by raphaeljolivet** [holdenk/spark-testing-base#219]
Hi, 

I have an issue having any test working for Spark 2.1 (2.1.0_0.8.0).
I have the following error, both on Linux and Windows : 
 
`
java.io.IOException: failure to login: No LoginModules configured for hadoop_simple
  at org.apache.hadoop.security.UserGroupInformation.loginUserFromSubject(UserGroupInformation.java:751)
  at org.apache.hadoop.security.UserGroupInformation.getLoginUser(UserGroupInformation.java:688)
  at org.apache.hadoop.security.UserGroupInformation.getCurrentUser(UserGroupInformation.java:572)
  at org.apache.spark.util.Utils$$anonfun$getCurrentUserName$1.apply(Utils.scala:2405)
  at org.apache.spark.util.Utils$$anonfun$getCurrentUserName$1.apply(Utils.scala:2405)
  at scala.Option.getOrElse(Option.scala:121)
  at org.apache.spark.util.Utils$.getCurrentUserName(Utils.scala:2405)
  at org.apache.spark.SparkContext.<init>(SparkContext.scala:295)
  at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2313)
  at com.holdenkarau.spark.testing.SharedSparkContext$class.beforeAll(SharedSparkContext.scala:45)
  ...
  Cause: javax.security.auth.login.LoginException: No LoginModules configured for hadoop_simple
  at javax.security.auth.login.LoginContext.init(LoginContext.java:272)
  at javax.security.auth.login.LoginContext.<init>(LoginContext.java:389)
  at org.apache.hadoop.security.UserGroupInformation.newLoginContext(UserGroupInformation.java:462)
  at org.apache.hadoop.security.UserGroupInformation.loginUserFromSubject(UserGroupInformation.java:723)
  at org.apache.hadoop.security.UserGroupInformation.getLoginUser(UserGroupInformation.java:688)
  at org.apache.hadoop.security.UserGroupInformation.getCurrentUser(UserGroupInformation.java:572)
  at org.apache.spark.util.Utils$$anonfun$getCurrentUserName$1.apply(Utils.scala:2405)
  at org.apache.spark.util.Utils$$anonfun$getCurrentUserName$1.apply(Utils.scala:2405)
  at scala.Option.getOrElse(Option.scala:121)
  at org.apache.spark.util.Utils$.getCurrentUserName(Utils.scala:2405)
`

I am also using spark-testing-base for Spark 1.6 and do not encounter this issue.
Could you please advise a workaround ?

Thanks in advance.

**Comment by raphaeljolivet** [comment]
I finally found the issue : 
I need to set an environement var : SPARK_USER=$USER
