### ISSUE TITLE
Hive support lost when upgrading from spark-testing-base 2.2.0_0.9.0 to 2.3.0_0.9.0

### ISSUE THREAD

**Issue by thomasdziedzic-pd** [holdenk/spark-testing-base#234]
I have the following minimal test case:

I was using spark 2.2.0 with spark-testing-base 2.2.0_0.9.0 and the test passed.
When bumping the dependencies to spark 2.3.0 and spark-testing-base to 2.3.0_0.9.0 the same test fails.

Here is the minimal test case:

```
import org.scalatest.FunSuite
import com.holdenkarau.spark.testing.DatasetSuiteBase

class HiveTest extends FunSuite with DatasetSuiteBase {
  import spark.implicits._

  test("hive support") {
    spark.sql("create table test as select 1 as a")
  }
}
```
this test fails with the following message.

```
[info] HiveTest:
18/03/23 15:05:14 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
18/03/23 15:05:16 WARN SparkContext: Using an existing SparkContext; some configuration may not take effect.
[info] - hive support *** FAILED ***
[info]   org.apache.spark.sql.AnalysisException: Hive support is required to CREATE Hive TABLE (AS SELECT);;
[info] 'CreateTable `test`, org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe, ErrorIfExists
[info] +- Project [1 AS a#0]
[info]    +- OneRowRelation
[info]   at org.apache.spark.sql.execution.datasources.HiveOnlyCheck$$anonfun$apply$12.apply(rules.scala:384)
[info]   at org.apache.spark.sql.execution.datasources.HiveOnlyCheck$$anonfun$apply$12.apply(rules.scala:382)
[info]   at org.apache.spark.sql.catalyst.trees.TreeNode.foreach(TreeNode.scala:117)
[info]   at org.apache.spark.sql.execution.datasources.HiveOnlyCheck$.apply(rules.scala:382)
[info]   at org.apache.spark.sql.execution.datasources.HiveOnlyCheck$.apply(rules.scala:380)
[info]   at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$2.apply(CheckAnalysis.scala:349)
[info]   at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$2.apply(CheckAnalysis.scala:349)
[info]   at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
[info]   at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
[info]   at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$class.checkAnalysis(CheckAnalysis.scala:349)
[info]   ...
[info] ScalaTest
[info] Run completed in 4 seconds, 530 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 0, failed 1, canceled 0, ignored 0, pending 0
[info] *** 1 TEST FAILED ***
[error] Failed: Total 1, Failed 1, Errors 0, Passed 0
[error] Failed tests:
[error]         HiveTest
[error] (test:testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 26 s, completed Mar 23, 2018 3:05:17 PM
```

**Comment by holdenk** [comment]
Thanks for the issue! Can you share your build file? I’m in Canada today but I’ll try and take a look on Monday.

**Comment by thomasdziedzic-pd** [comment]
Sure, appreciate your time!

```
val sparkVersion = "2.3.0"

// give the user a nice default project!
lazy val root = (project in file(".")).
  settings(
    inThisBuild(List(
      scalaVersion := "2.11.12"
    )),
    name := "minimal-test-case",
    version := "0.0.1",
    javacOptions ++= Seq("-source", "1.8", "-target", "1.8"),
    parallelExecution in Test := false,
    fork := true,
    javaOptions ++= Seq("-Xms512M", "-Xmx2048M", "-XX:+CMSClassUnloadingEnabled"),
    libraryDependencies ++= Seq(
      "org.scalatest" %% "scalatest" % "3.0.1" % Test,
      "com.holdenkarau" %% "spark-testing-base" % s"${sparkVersion}_0.9.0" % Test,
      "org.apache.spark" %% "spark-core" % sparkVersion % "provided",
      "org.apache.spark" %% "spark-sql" % sparkVersion % "provided",
      "org.apache.spark" %% "spark-hive" % sparkVersion % "provided"
    ),
    scalacOptions ++= Seq("-deprecation", "-unchecked"),
    pomIncludeRepository := { x => false }
  )
```

I left you a variable at the top to easily switch between 2.2.0 and 2.3.0 :)

**Comment by abdurrahman-lumos** [comment]
Would there happen to be an update for this? I am also experiencing the same issue.

**Comment by thomasdziedzic-pd** [comment]
I can confirm that the following updated minimal test case passes under spark 2.3.0.

```
import org.scalatest.FunSuite
import com.holdenkarau.spark.testing.DatasetSuiteBase
import org.apache.spark.SparkConf
import org.apache.spark.sql.internal.StaticSQLConf.CATALOG_IMPLEMENTATION

class HiveTest extends FunSuite with DatasetSuiteBase {
  override def conf: SparkConf = super.conf.set(CATALOG_IMPLEMENTATION.key, "hive")

  import spark.implicits._

  test("hive support") {
    spark.sql("create table test as select 1 as a")
  }
}
```

**Comment by thomasdziedzic-pd** [comment]
Looks like this workaround doesn't work when there is more than 1 test class.

I have the following setup:

`cat src/test/scala/HiveTest.scala`

```
import org.scalatest.FunSuite
import com.holdenkarau.spark.testing.DatasetSuiteBase
import org.apache.spark.SparkConf
import org.apache.spark.sql.internal.StaticSQLConf.CATALOG_IMPLEMENTATION

class HiveTest extends FunSuite with DatasetSuiteBase {
  override def conf: SparkConf = super.conf.set(CATALOG_IMPLEMENTATION.key, "hive")

  test("hive support") {
    spark.sql("select 1")
  }
}
```

`cat src/test/scala/AnotherHiveTest.scala`

```
import org.scalatest.FunSuite
import com.holdenkarau.spark.testing.DatasetSuiteBase
import org.apache.spark.SparkConf
import org.apache.spark.sql.internal.StaticSQLConf.CATALOG_IMPLEMENTATION

class AnotherHiveTest extends FunSuite with DatasetSuiteBase {
  override def conf: SparkConf = super.conf.set(CATALOG_IMPLEMENTATION.key, "hive")

  test("hive support") {
    spark.sql("select 1")
  }
}
```

Which produces the error (full log attached):

```
18/05/16 08:46:05 ERROR Schema: Failed initialising database.
Unable to open a test connection to the given database. JDBC url = jdbc:derby:;databaseName=metastore_db;create=true, username = APP. Terminating connection pool (set lazyInit to true if you expect to start your database after your app). Original Exception: ------
java.sql.SQLException: Failed to start database 'metastore_db' with class loader org.apache.spark.sql.hive.client.IsolatedClientLoader$$anon$1@6c550067, see the next exception for details.
```
[error.log](https://github.com/holdenk/spark-testing-base/files/2009389/error.log)

**Comment by Shasidhar** [comment]
I think the problem is sqlcontext is not handled gracefully, I'm able to overcome this problem by clearing out the locks inside the `metastore_db` folder after each test with a simple afterAll clause.

```
override def afterAll() {
    super.afterAll()
    new File("metastore_db/db.lck").delete()
    new File("metastore_db/dbex.lck").delete()
  }
```
It's not really a great workaround but that's doing the job for now.

**Comment by Cyberness** [comment]
> Looks like this workaround doesn't work when there is more than 1 test class.

That's because Derby is ran in embedded mode and only one process (JVM) can use it at the time. Once you have more than one test suite (class) and I think because of recommended setting `fork in Test := true` both test suites are trying to start and access same metastore_db and collide. The workaround is a bit tricky, but possible. You can start metastoreDB as a NetworkServer in Derby and then set `javax.jdo.option.ConnectionURL` parameter to connect to it. Or you can put everything in one test suite. Or you can set `fork in Test := false`. But two former didn't work for me, because in our code we also create our own instance of HiveMetaStoreClient which in local mode tries to deploy another version of metastore_db and it fails of course. So, we had to mess with a NetworkServer in Derby.

**Comment by LvffY** [comment]
Hello

Is there any update on this issue ? I think I fall into the same error and I would like to know if we still need to use the differents workarounds described here.

Thanks

**Comment by ashkan-leo** [comment]
The workaround does not work for me (using `2.4.3_0.14.0`). I override the spark conf object and set the metastore path:
```scala
  override def conf =
    super.conf
      .set(CATALOG_IMPLEMENTATION.key, "hive")
      .set("spark.sql.warehouse.dir", "file:/tmp/")
```
However, when the tests are running the metastore still points to an invalid directory.

**Comment by pash0002** [comment]
`class TestSpec extends FunSuite with SharedSparkContext with DataFrameSuiteBase {

  override def conf: SparkConf = super.conf.set(CATALOG_IMPLEMENTATION.key, "hive")

  test("spark sql testing") {
    spark.sql("create database if not exists test_db LOCATION '/home/prasad.kudale/test_db.db'")
    spark.sql("create table test_db.table1(col string)")
  }
}`

The following error occur while running above program
An exception or error caused a run to abort: HIVE_STATS_JDBC_TIMEOUT 
java.lang.NoSuchFieldError: HIVE_STATS_JDBC_TIMEOUT

**Comment by kuheli004** [comment]
I am facing the same issue .Please let me know the workaround.

**Comment by nikken7101** [comment]
> Looks like this workaround doesn't work when there is more than 1 test class.

Hi, I encountered the same issue and managed to resolve it with the following code:

```scala
override def conf: SparkConf = super.conf
  .set("spark.sql.catalogImplementation", "hive")
  .set(
	"spark.hadoop.javax.jdo.option.ConnectionURL",
	s"jdbc:derby:;databaseName=$localMetastorePath;create=true"
  )
```

The code at [https://github.com/holdenk/spark-testing-base/blob/v1.4.3/core/src/main/2.0/scala/com/holdenkarau/spark/testing/DataFrameSuiteBase.scala#L148](https://github.com/holdenk/spark-testing-base/blob/v1.4.3/core/src/main/2.0/scala/com/holdenkarau/spark/testing/DataFrameSuiteBase.scala#L148) attempts to set the metastore path to `$tempDir/metastore`, but it doesn't seem to take effect properly. 
As a result, the context automatically creates a `metastore_db` in the current directory, leading to conflicts with the metastore directory.

To override configurations from `hive-site.xml`, we need to prefix the configuration key with `spark.hadoop`. 
Therefore, we should use the key `spark.hadoop.javax.jdo.option.ConnectionURL` instead of `javax.jdo.option.ConnectionURL`.

**Comment by nikken7101** [comment]
My colleague pointed out a misunderstanding in my previous comment.

The presence or absence of the `spark.hadoop` prefix doesn't matter, and the following is sufficient:

```scala
override def conf: SparkConf = super.conf
  .set("spark.sql.catalogImplementation", "hive")
  .set(
	"javax.jdo.option.ConnectionURL",
	s"jdbc:derby:;databaseName=$localMetastorePath;create=true"
  )
```
This is because Spark configurations are automatically merged into Hadoop configurations.

The issue seems to be that the conf settings by `builder.config` in this section of the code are not being applied to `sc._conf`.
https://github.com/holdenk/spark-testing-base/blob/v1.4.3/core/src/main/2.0/scala/com/holdenkarau/spark/testing/DataFrameSuiteBase.scala#L160-L205

The initialization of the SparkContext before `builder.getOrCreate` results in `sc._conf` being fixed, and the settings made with `builder.config` are not reflected. 
Therefore, the contents of `spark.conf` and `spark.sparkContext.getConf`  (`sc._conf`) are inconsistent. 
`spark.sql.catalogImplementation` and `javax.jdo.option.ConnectionURL` are not reflected in `spark.sparkContext.getConf`.

It seems that in relation to HiveCatalog, the conf of `sc.getConf` is referred to, not `spark.conf`. This is causing a series of problems.
