### ISSUE TITLE
ValueError: please use 'pytest' pypi package instead of 'py.test'

### ISSUE THREAD

**Issue by pchundi** [holdenk/spark-testing-base#24]
Hi,

I have tried installing the testing framework locally with Python version 2.7. 
```
pchundi@uvbox:~/IdeaProjects/spark-testing-base/python$ sudo python setup.py install
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'test_requires'
  warnings.warn(msg)
running install
running bdist_egg
running egg_info
writing requirements to sparktestingbase.egg-info/requires.txt
writing sparktestingbase.egg-info/PKG-INFO
writing top-level names to sparktestingbase.egg-info/top_level.txt
writing dependency_links to sparktestingbase.egg-info/dependency_links.txt
reading manifest file 'sparktestingbase.egg-info/SOURCES.txt'
writing manifest file 'sparktestingbase.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/sparktestingbase
copying build/lib.linux-x86_64-2.7/sparktestingbase/streamingtestcase.py -> build/bdist.linux-x86_64/egg/sparktestingbase
copying build/lib.linux-x86_64-2.7/sparktestingbase/__init__.py -> build/bdist.linux-x86_64/egg/sparktestingbase
creating build/bdist.linux-x86_64/egg/sparktestingbase/test
copying build/lib.linux-x86_64-2.7/sparktestingbase/test/reuse_spark_context_test.py -> build/bdist.linux-x86_64/egg/sparktestingbase/test
copying build/lib.linux-x86_64-2.7/sparktestingbase/test/helloworld_test.py -> build/bdist.linux-x86_64/egg/sparktestingbase/test
copying build/lib.linux-x86_64-2.7/sparktestingbase/test/simple_streaming_test.py -> build/bdist.linux-x86_64/egg/sparktestingbase/test
copying build/lib.linux-x86_64-2.7/sparktestingbase/test/__init__.py -> build/bdist.linux-x86_64/egg/sparktestingbase/test
copying build/lib.linux-x86_64-2.7/sparktestingbase/test/simple_test.py -> build/bdist.linux-x86_64/egg/sparktestingbase/test
copying build/lib.linux-x86_64-2.7/sparktestingbase/testcase.py -> build/bdist.linux-x86_64/egg/sparktestingbase
copying build/lib.linux-x86_64-2.7/sparktestingbase/utils.py -> build/bdist.linux-x86_64/egg/sparktestingbase
byte-compiling build/bdist.linux-x86_64/egg/sparktestingbase/streamingtestcase.py to streamingtestcase.pyc
byte-compiling build/bdist.linux-x86_64/egg/sparktestingbase/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/sparktestingbase/test/reuse_spark_context_test.py to reuse_spark_context_test.pyc
byte-compiling build/bdist.linux-x86_64/egg/sparktestingbase/test/helloworld_test.py to helloworld_test.pyc
byte-compiling build/bdist.linux-x86_64/egg/sparktestingbase/test/simple_streaming_test.py to simple_streaming_test.pyc
byte-compiling build/bdist.linux-x86_64/egg/sparktestingbase/test/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/sparktestingbase/test/simple_test.py to simple_test.pyc
byte-compiling build/bdist.linux-x86_64/egg/sparktestingbase/testcase.py to testcase.pyc
byte-compiling build/bdist.linux-x86_64/egg/sparktestingbase/utils.py to utils.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying sparktestingbase.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying sparktestingbase.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying sparktestingbase.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying sparktestingbase.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying sparktestingbase.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/sparktestingbase-0.0.7_snapshot-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing sparktestingbase-0.0.7_snapshot-py2.7.egg
Removing /usr/local/lib/python2.7/dist-packages/sparktestingbase-0.0.7_snapshot-py2.7.egg
Copying sparktestingbase-0.0.7_snapshot-py2.7.egg to /usr/local/lib/python2.7/dist-packages
sparktestingbase 0.0.7-snapshot is already the active version in easy-install.pth

Installed /usr/local/lib/python2.7/dist-packages/sparktestingbase-0.0.7_snapshot-py2.7.egg
Processing dependencies for sparktestingbase==0.0.7-snapshot
Searching for py.test
Reading https://pypi.python.org/simple/py.test/
Best match: py.test 0.0
Downloading https://pypi.python.org/packages/source/p/py.test/py.test-0.0.tar.gz#md5=9a5bcfc8ad06500ddd3a0fe3aa7965f6
Processing py.test-0.0.tar.gz
Writing /tmp/easy_install-z5O08t/py.test-0.0/setup.cfg
Running py.test-0.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-z5O08t/py.test-0.0/egg-dist-tmp-dOfqou
Traceback (most recent call last):
  File "setup.py", line 22, in <module>
    'unittest2'
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 73, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 96, in do_egg_install
    cmd.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 381, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 597, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 648, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 694, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 620, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 858, in best_match
    return self.obtain(req, installer) # try and download/install
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 870, in obtain
    return installer(requirement)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 616, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 646, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 834, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1040, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1025, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 50, in run_setup
    lambda: execfile(
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 100, in run
    return func()
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 52, in <lambda>
    {'__file__':setup_script, '__name__':'__main__'}
  File "setup.py", line 6, in <module>
    author='Holden Karau',
ValueError: please use 'pytest' pypi package instead of 'py.test'
```
Should I install any dependencies before installing the framework?

**Comment by pchundi** [comment]
There was typo in the setup.py, I corrected it. Here is a pull request.
https://github.com/holdenk/spark-testing-base/pull/25

**Comment by holdenk** [comment]
Thanks for fixing this.
