### ISSUE TITLE
Dependency issues with  spark-testing-base_2.10, version 1.6.3_0.10.0

### ISSUE THREAD

**Issue by kingledion** [holdenk/spark-testing-base#265]
I use a dependency on `com.holdenkarau:spark-testing-base_2.10:jar:1.6.3_0.10.0`. In `mvn dependency:tree`, my dependency tree looks like: 

```
[INFO] +- com.holdenkarau:spark-testing-base_2.10:jar:1.6.3_0.10.0:test
[INFO] |  +- org.scalatest:scalatest_2.10:jar:3.0.1:test
[INFO] |  |  +- org.scalactic:scalactic_2.10:jar:3.0.1:test
[INFO] |  |  \- org.scala-lang:scala-reflect:jar:2.10.6:provided
```

However, this version of scalatest  and scalactic do not compile. On `mvn test` I get the following test compile error:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project Kazoo: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: There was an error in the forked process
[ERROR] java.lang.NoClassDefFoundError: org/scalatest/PendingNothing
[ERROR]         at java.lang.Class.getDeclaredMethods0(Native Method)
[ERROR]         at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
[ERROR]         at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
[ERROR]         at java.lang.Class.getMethod0(Class.java:3018)
[ERROR]         at java.lang.Class.getMethod(Class.java:1784)
```

I am able to fix this error by forcing the scalatest dependency back to version 2. For example, in my pom.xml, I can use:

```
        <dependency>
            <groupId>com.holdenkarau</groupId>
            <artifactId>spark-testing-base_2.10</artifactId>
            <version>1.6.3_0.10.0</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.scalatest</groupId>
                    <artifactId>scalatest_2.10</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.scalatest</groupId>
            <artifactId>scalatest_2.10</artifactId>
            <version>2.2.1</version>
        </dependency>
```

This compiles properly. 

Does spark-testing-base 1.6.3_0.10.0 really depend on scalatest 3.0.1? Or should it depend on an earlier version?

**Comment by kingledion** [comment]
An alternate solution that I am currently using is to go back to spark-testing-base 1.6.3_0.5.0, and remove the scalatest dependency, relying on the dependency within spark-testing-base.

In the `dependency:tree` this looks like:

```
 \- com.holdenkarau:spark-testing-base_2.10:jar:1.6.3_0.5.0:test
+- org.scalatest:scalatest_2.10:jar:2.2.6:test
```
