### ISSUE TITLE
Streaming Context is stopped prematurely, which prevents sequence of batches to be executed fully, visible on slower machines

### ISSUE THREAD

**Issue by elyast** [holdenk/spark-testing-base#27]
Hi,

I am struggling with running SparkStreaming tests on slower boxes, and apparently the streaming context is being closed to soon, (before every batch could be processed), my code:
```scala
class StreamToFileDumperSparkTest  extends StreamingActionBase {
  test("smoke integration test for dumper transformation") {
     val input = List(List(data1), List(data2), List(data3))
     runAction(input, (s: DStream[String]) => s.foreachRDD(/*save some files*/))
     // here I do waiting for files to be available
     val result = sc.textFile(some_path).collect().sorted
     result should equal(inputData)
  }
}
```

Exception that shows my suspicion about streaming context be closed to soon is following:
```
15/11/17 12:02:24 INFO DAGScheduler: Submitting ResultStage 1 (MapPartitionsRDD[15] at foreachRDD at StreamToFileDumper.scala:57), which is now runnable
Exception in thread "streaming-job-executor-0" java.lang.Error: java.lang.InterruptedException
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1151)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:503)
	at org.apache.spark.scheduler.JobWaiter.awaitResult(JobWaiter.scala:73)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:559)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1822)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1835)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1912)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1.apply$mcV$sp(PairRDDFunctions.scala:1124)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1.apply(PairRDDFunctions.scala:1065)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1.apply(PairRDDFunctions.scala:1065)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:306)
	at org.apache.spark.rdd.PairRDDFunctions.saveAsHadoopDataset(PairRDDFunctions.scala:1065)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$4.apply$mcV$sp(PairRDDFunctions.scala:989)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$4.apply(PairRDDFunctions.scala:965)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$4.apply(PairRDDFunctions.scala:965)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:306)
	at org.apache.spark.rdd.PairRDDFunctions.saveAsHadoopFile(PairRDDFunctions.scala:965)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$3.apply$mcV$sp(PairRDDFunctions.scala:951)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$3.apply(PairRDDFunctions.scala:951)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$3.apply(PairRDDFunctions.scala:951)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:306)
	at org.apache.spark.rdd.PairRDDFunctions.saveAsHadoopFile(PairRDDFunctions.scala:950)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$2.apply$mcV$sp(PairRDDFunctions.scala:909)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$2.apply(PairRDDFunctions.scala:907)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$2.apply(PairRDDFunctions.scala:907)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:306)
	at org.apache.spark.rdd.PairRDDFunctions.saveAsHadoopFile(PairRDDFunctions.scala:907)
	at org.apache.spark.rdd.RDD$$anonfun$saveAsTextFile$2.apply$mcV$sp(RDD.scala:1444)
	at org.apache.spark.rdd.RDD$$anonfun$saveAsTextFile$2.apply(RDD.scala:1432)
	at org.apache.spark.rdd.RDD$$anonfun$saveAsTextFile$2.apply(RDD.scala:1432)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:306)
	at org.apache.spark.rdd.RDD.saveAsTextFile(RDD.scala:1432)
	at com.nokia.ph.kinesis2s3.spark.StreamToFileDumper.save(StreamToFileDumper.scala:45)
	at com.nokia.ph.kinesis2s3.spark.StreamToFileDumper$$anonfun$process$1.apply(StreamToFileDumper.scala:57)
	at com.nokia.ph.kinesis2s3.spark.StreamToFileDumper$$anonfun$process$1.apply(StreamToFileDumper.scala:57)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(ForEachDStream.scala:42)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ForEachDStream.scala:40)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ForEachDStream.scala:40)
	at org.apache.spark.streaming.dstream.DStream.createRDDWithLocalProperties(DStream.scala:399)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply$mcV$sp(ForEachDStream.scala:40)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply(ForEachDStream.scala:40)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply(ForEachDStream.scala:40)
	at scala.util.Try$.apply(Try.scala:161)
	at org.apache.spark.streaming.scheduler.Job.run(Job.scala:34)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply$mcV$sp(JobScheduler.scala:218)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply(JobScheduler.scala:218)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply(JobScheduler.scala:218)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler.run(JobScheduler.scala:217)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	... 2 more
15/11/17 12:02:24 INFO JobScheduler: Stopped JobScheduler
```

**Comment by holdenk** [comment]
Huh that certainly is weird - what sort of speed boxes? I'll take a look this week but I'm travelling so it might be a bit before I can work on a fix.

**Comment by elyast** [comment]
Its: 
```
Linux svl-build21 3.13.0-36-generic # Ubuntu 14.04
6 GB RAM
2x Intel(R) Xeon(R) CPU           E5540  @ 2.53GHz
```

Tests are executed through jenkins slave

so far what I did as a workaround I extend StreamingActionBase in following way:
```scala
trait GracefulStreamingActionBase extends StreamingActionBase {
  override def withStreamingContext(outputStreamSSC: TestStreamingContext)(block: (TestStreamingContext) => Unit): Unit = {
    ...
    outputStreamSSC.stop(stopSparkContext = false, stopGracefully = true)
    ...
  }

  override def runActionStream(ssc: TestStreamingContext, numBatches: Int) {
    ...
    // This actually sucks, since it will always wait this amount of time...
    ssc.awaitTerminationOrTimeout(5000)
    Thread.sleep(3000) // Give some time for the forgetting old RDDs to complete
    ...
  }
}
```

**Comment by holdenk** [comment]
Thanks - and sorry about the bug. I'll see what I can do in the way of a
proper solution.

On Thursday, November 19, 2015, Lukasz Jastrzebski <notifications@github.com>
wrote:

> Its:
>
> Linux svl-build21 3.13.0-36-generic # Ubuntu 14.04
> 6 GB RAM
> 2x Intel(R) Xeon(R) CPU           E5540  @ 2.53GHz
>
> Tests are executed through jenkins slave
>
> so far what I did as a workaround I extend StreamingActionBase in
> following way:
>
> trait GracefulStreamingActionBase extends StreamingActionBase {
>   override def withStreamingContext(outputStreamSSC: TestStreamingContext)(block: (TestStreamingContext) => Unit): Unit = {
>     ...
>     outputStreamSSC.stop(stopSparkContext = false, stopGracefully = true)
>     ...
>   }
>
>   override def runActionStream(ssc: TestStreamingContext, numBatches: Int) {
>     ...
>     // This actually sucks, since it will always wait this amount of time...
>     ssc.awaitTerminationOrTimeout(5000)
>     Thread.sleep(3000) // Give some time for the forgetting old RDDs to complete
>     ...
>   }
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/holdenk/spark-testing-base/issues/27#issuecomment-157916509>
> .
>


-- 
Cell : 425-233-8271
Twitter: https://twitter.com/holdenkarau

**Comment by jnadler** [comment]
So... this is my bad.    In StreamingSuiteBase, because non-action tests generate output it can wait for the output to indicate that the correct number of intervals have run...

```while (output.size < numExpectedOutput...```

But when testing an action there is no output so what to replace it with?   I have one idea - will give it a test and send a PR if it works.

**Comment by jnadler** [comment]
I just put in a PR - @elyast would you please test my changes and let @holdenk know if it looks good?   Thanks.

**Comment by elyast** [comment]
@jnadler sure I will give it a spin

**Comment by elyast** [comment]
@jnadler after I patched your pull request it tends to be working I repeat it several times to make sure there is no timing issue but it seems to work fine. Thanks 

Please fix adding streamingListener

**Comment by jnadler** [comment]
Yes looks like I made a merge error (I'm running an older version of spark-testing-base).   I'll update the PR.   Thanks for testing this.

**Comment by elyast** [comment]
its been merged already closing
