### ISSUE TITLE
Which version of Python are supported ?

### ISSUE THREAD

**Issue by mmistroni** [holdenk/spark-testing-base#282]
Hello
 i am using the spark-testing-base python version. 
Have noticed that running Python2.7 works absolutely fine, while when i move to Python3.7 i am getting this massive exception (this happens from both running via pycharm and command line)
This is my (Broken) Setup
Machine: Windows 10 Laptop
Spark Installed Version: spark-2.2.0-bin-hadoop2.7
Python Version:  3.7.1

I am *guessing*  something breaks between my spark version and my python version.  Appreciate some hints...
Kind regards
  Marco

C:\Users\marco\AppData\Local\Programs\Python\Python37-32>python hello_test.py
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
19/02/08 22:25:53 ERROR SparkUncaughtExceptionHandler: Uncaught exception in thread Thread[main,5,main]
java.util.NoSuchElementException: key not found: _PYSPARK_DRIVER_CALLBACK_HOST
        at scala.collection.MapLike$class.default(MapLike.scala:228)
        at scala.collection.AbstractMap.default(Map.scala:59)
        at scala.collection.MapLike$class.apply(MapLike.scala:141)
        at scala.collection.AbstractMap.apply(Map.scala:59)
        at org.apache.spark.api.python.PythonGatewayServer$$anonfun$main$1.apply$mcV$sp(PythonGatewayServer.scala:50)
        at org.apache.spark.util.Utils$.tryOrExit(Utils.scala:1262)
        at org.apache.spark.api.python.PythonGatewayServer$.main(PythonGatewayServer.scala:37)
        at org.apache.spark.api.python.PythonGatewayServer.main(PythonGatewayServer.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:755)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
E
======================================================================
ERROR: test_basic (__main__.HelloWorldTest)
Test a parallelize & collect.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\marco\AppData\Roaming\Python\Python37\site-packages\sparktestingbase\testcase.py", line 40, in setUp
    self.sc = SparkContext(self.getMaster())
  File "C:\Users\marco\AppData\Roaming\Python\Python37\site-packages\pyspark\context.py", line 115, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "C:\Users\marco\AppData\Roaming\Python\Python37\site-packages\pyspark\context.py", line 298, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "C:\Users\marco\AppData\Roaming\Python\Python37\site-packages\pyspark\java_gateway.py", line 94, in launch_gateway
    raise Exception("Java gateway process exited before sending its port number")
Exception: Java gateway process exited before sending its port number

**Comment by mmistroni** [comment]
No, i am actually unable to reproduce. I am not sure if it was because of settings or IDE. I have set PYCharm to run unit tests as pytest and bot unittest2 and it seems there are no issues. Closing this , will have a look at my environment more and run further tests
