### ISSUE TITLE
including spark-testing-base gives me "No FileSystem for scheme: s3n" at DataFrameReader.load

### ISSUE THREAD

**Issue by RAbraham** [holdenk/spark-testing-base#40]
Hi Holden,
This could be a sbt newbie question and just let me know if it is(and I'll research more): 

When I add a dependency to `spark-testing-base` in my `sbt` file, previously working code interfacing with the `spark-redshift` package, specifically `DataFrameReader.load` code fails with the following error:
```
Exception in thread "main" java.io.IOException: No FileSystem for scheme: s3n
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2584)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2591)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:91)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2630)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2612)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:370)
	at com.databricks.spark.redshift.Utils$.assertThatFileSystemIsNotS3BlockFileSystem(Utils.scala:124)
	at com.databricks.spark.redshift.RedshiftRelation.<init>(RedshiftRelation.scala:48)
	at com.databricks.spark.redshift.DefaultSource.createRelation(DefaultSource.scala:49)
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:125)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:114)
..

``` 
The calling code is:
```
sqlContext.read
      .format("com.databricks.spark.redshift")
      .option("url", redshift_url)
      .option("query", query)
      .option("tempdir", "s3n://i-love-unit-testing/")
      .load() // <- fails here.
```

My spark related sbt additions are:
```
libraryDependencies += "org.apache.spark" %% "spark-core" % "1.5.2" % "provided"
libraryDependencies += "org.apache.spark" %% "spark-mllib" % "1.5.2" % "provided"
libraryDependencies += "org.apache.spark" %% "spark-sql" % "1.5.2" % "provided"
libraryDependencies += "com.holdenkarau" %% "spark-testing-base" % "1.5.1_0.2.1" % "provided"
libraryDependencies += "com.databricks" %% "spark-csv" % "latest.release"
libraryDependencies += "com.databricks" %% "spark-redshift" % "latest.release"
```
I tried without `provided` and it did not work as well.

**Comment by holdenk** [comment]
That is a little weird, my guess is were conflicting with something in 1.5.2 - I'll publish a new version built for 1.5.2 but could you try adding `intransitive` and manually including scalacheck as well?

**Comment by holdenk** [comment]
I'm going to go ahead and close this issue for now, I think this issue has been fixed by making minor version releases so available.
